# “Git push -f” или после нас хоть потоп

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных.

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией.
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

 С этими библиотеками вы будете знакомится дальше на курсе, а пока давайте попрактикуемся в решении базовых задач на  чистом Python.

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [ ]:
def share_bread(N: int, K: int) -> tuple:
    """
    Функция распределяет K кусков хлеба между N хоббитов поровну.
    
    Args:
        N (int): количество хоббитов
        K (int): количество кусков хлеба

    Raises:
        ValueError: ошибка при делении на ноль

    Returns:
        tuple: сколько кусков достанется каждому хоббиту и сколько останется в корзине
    """
    
    if K == 0:
        raise ValueError('K couldn\\t be 0')
    x = K // N
    y = K - x * N
    
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [ ]:
def leap_year(year: int) -> str:
    """
    Является ли год високосным или нет

    Args:
        year (int): год

    Returns:
        str: результат проверки
    """
    
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        text_result = "YOU SHALL PASS"
    else:
        text_result = "YOU SHALL NOT PASS"
        
    return text_result

assert leap_year(5) == 'YOU SHALL NOT PASS'




## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>


Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

**Подсказка:** используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [ ]:
def amulet_area(a: int|float, b: int|float, c: int|float) -> float:
    """  
    Вычисляет площадь треугольника по формуле Герона.

    Args:
        a (int | float): первая сторона треугольника
        b (int | float): вторая сторона треугольника
        c (int | float): третья сторона треугольника

    Returns:
        float: площадь треугольника
    """
    
    p = a + b + c
    s = p / 2
    S = (s * (s - a) * (s - b) * (s - c)) ** 0.5
    
    return S

assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - написать функцию под каждую из них. Важное условие - используйте только базовые функции для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [ ]:
from typing import Union, List

import math
import numpy as np


def cal_euclidean(a: List[Union[int, float]], b: List[Union[int, float]]) -> float:
    """
    Вычисляет евклидово расстояние между двумя векторами a и b.
    
    Args:
        a (List[Union[int, float]]): вектор а в виде списка чисел
        b (List[Union[int, float]]): вектор b в виде списка чисел

    Raises:
        ValueError: если длины векторов не совпадают

    Returns:
        float: расстояние между векторами a и b
    """
    
    if len(a) != len(b):
        raise ValueError('Length of a and b must be the same')
    
    distance = 0
    for i in range( len(a) ):
        diff = a[i] - b[i]
        distance = distance + diff ** 2
    
    distance = distance ** 0.5
    
    return distance

def cal_manhattan(a: List[Union[int, float]], b: List[Union[int, float]]) -> float:
    """
    Эта функция вычисляет манхэттенское расстояние между двумя векторами a и b.
    Args:
        a (List[Union[int, float]]): вектор а в виде списка чисел
        b (List[Union[int, float]]): вектор b в виде списка чисел       
        
    Raises:
        ValueError: если длины векторов не совпадают    
        
    Returns:
        float: манхэттенское расстояние между векторами a и b
    """ 
    
    if len(a) != len(b):
        raise ValueError('Length of a and b must be the same')
    
    distance = 0
    for i in range( len(a) ):
        abs_diff = abs(a[i] - b[i])
        distance = distance + abs_diff  

    return distance

def cal_cosine(a: List[Union[int, float]], b: List[Union[int, float]]) -> float:
    """
    Эта функция вычисляет косинусное расстояние между двумя векторами a и b.
    
    Args:
        a (List[Union[int, float]]): вектор а в виде списка чисел
        b (List[Union[int, float]]): вектор b в виде списка чисел
        
    Raises:
        ValueError: если длины векторов не совпадают    
        
    Returns:
        float: косинусное расстояние между векторами a и b
    """
    
    if len(a) != len(b):
        raise ValueError('Length of a and b must be the same')  
    
    # Инициализация переменных для вычислений
    dot_product = 0
    magnitude1 = 0
    magnitude2 = 0
    
    # Вычисление скалярного произведения (числитель) 
    for i in range(len(a)):
        dot_product += a[i] * b[i]
        magnitude1 += a[i] * a[i]  # Сумма квадратов a
        magnitude2 += b[i] * b[i]  # Сумма квадратов b
    
    # Вычисление норм (длин) векторов с использованием квадратного корня (math.sqrt)
    # Используем math.sqrt из стандартной библиотеки Python
    
    mag1_sqrt = math.sqrt(magnitude1)
    mag2_sqrt = math.sqrt(magnitude2)
    
    # Проверка деления на ноль (если один из векторов нулевой)
    if mag1_sqrt == 0 or mag2_sqrt == 0:
        raise ValueError('One of the vectors is zero vector, cannot compute cosine distance.')  

    # Вычисление косинусного сходства (меры)
    cosine_similarity = dot_product / (mag1_sqrt * mag2_sqrt)
    
    # Вычисление косинусного расстояния
    distance = 1 - cosine_similarity
    
    return distance


a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)

print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

22.67156809750927
58
0.712106247896902


## Задача 5* (бонусное неоцениваемое задание)

**Замечание:** Поскольку библиотеку numpy мы будем подробно разбирать дальше, то это задание является бонусным, его выполнение необязательно для сдачи ДЗ и не влияет на итоговый балл. Как вариант, можете вернуться к нему после прохождения numpy ;)



Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в интервале от 0 до 1 остаются прежними

In [34]:
def normalize_array_min_max(arr):
    """
    Нормализует массив NumPy так, чтобы минимальное значение стало 0, 
    максимальное значение стало 1, а остальные значения масштабировались 
    пропорционально в диапазоне [0, 1].
    """
    # Находим минимальное и максимальное значения в исходном массиве
    min_val = np.min(arr)
    max_val = np.max(arr)
    
    # Проверка на случай, если все элементы в массиве одинаковы (деление на 0)
    if max_val == min_val:
        # Если все элементы одинаковы, возвращаем массив из нулей
        return np.zeros_like(arr)

    # Применяем формулу Min-Max масштабирования:
    # new_value = (old_value - min_val) / (max_val - min_val)
    normalized_arr = (arr - min_val) / (max_val - min_val)
    
    return normalized_arr

my_array = np.random.rand(100)
print(np.max(my_array), np.min(my_array))
print(my_array)

normalized_array = normalize_array_min_max(my_array)
print(np.max(normalized_array), np.min(normalized_array))
print(normalized_array)

0.9991229750375916 0.018871671153134262
[0.20097852 0.43291256 0.50145553 0.44909294 0.03864325 0.37167823
 0.28449792 0.6146717  0.90794977 0.0558875  0.13443114 0.58363254
 0.20519513 0.73439894 0.82566271 0.07820447 0.21152126 0.7552447
 0.8301504  0.68335179 0.90619947 0.1406343  0.83098822 0.11287828
 0.8499493  0.68089813 0.45419903 0.01999826 0.27932859 0.53141436
 0.88387255 0.27212453 0.80963687 0.50984374 0.09319832 0.7568531
 0.80900742 0.65047723 0.66373612 0.80670564 0.78140492 0.57898966
 0.34452058 0.09100869 0.68442795 0.58047291 0.66627953 0.59605675
 0.68761804 0.34292846 0.75337563 0.59758472 0.20901549 0.18861747
 0.04701494 0.90033742 0.5329961  0.14969084 0.67702316 0.28511661
 0.98908786 0.01887167 0.89032782 0.03609132 0.48745892 0.41572208
 0.48681816 0.68561838 0.14996355 0.86151235 0.94875342 0.36868412
 0.47480669 0.16093415 0.97054469 0.12318293 0.12804431 0.08004972
 0.20309379 0.21019354 0.55644717 0.22006045 0.98575719 0.27988483
 0.48696623 0.67832723 0

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы

In [35]:
# 1. Создаем array (матрицу) размером 5x6 с целыми числами в интервале [0, 50]
# np.random.randint(low, high, size) генерирует целые числа от low (включительно) до high (не включительно)
# Поэтому используем интервал от 0 до 51, чтобы включить 50.
matrix = np.random.randint(0, 51, size=(5, 6))

print("Созданная матрица 5x6:")
print(matrix)
print("-" * 30)

# 2. Находим индекс максимального элемента во всей матрице
# Сначала находим индекс максимального элемента в "спрямленном" массиве (flat index)
flat_max_index = np.argmax(matrix)

# Преобразуем "плоский" индекс в координаты (строка, колонка)
# matrix.shape[1] дает количество колонок (6)
row_index, col_index = np.unravel_index(flat_max_index, matrix.shape)

# 3. Печатаем информацию о максимальном элементе
max_value = matrix[row_index, col_index]
print(f"Максимальный элемент: {max_value}")
print(f"Находится по координатам: строка {row_index}, колонка {col_index}")
print("-" * 30)

# 4. Печатаем всю колонку, которая содержит этот максимальный элемент
# Используем срезы NumPy для выбора всех строк (:) в найденной колонке (col_index)
column_with_max = matrix[:, col_index]

print(f"Колонка {col_index}, содержащая максимальный элемент:")
print(column_with_max)

#my_array = ## Your code here
#selected_column = ## Your code here
#print('Shape: ',my_array.shape)
#print('Array')
#print(my_array)
#print(selected_column)

Созданная матрица 5x6:
[[36 18 48 17 24 42]
 [17 30 45 41 14  2]
 [43 24 26  0 30  0]
 [46 19  4 48 40 46]
 [ 7 21 50  2 45  3]]
------------------------------
Максимальный элемент: 50
Находится по координатам: строка 4, колонка 2
------------------------------
Колонка 2, содержащая максимальный элемент:
[48 45 26  4 50]


Напишите функцию, которая принимает на вход матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [37]:
def get_unique_rows(X):
    """
    Принимает матрицу X и возвращает новую матрицу, содержащую
    только уникальные строки исходной матрицы.
    """
    # np.unique(axis=0) ищет уникальные элементы вдоль оси строк и 
    # возвращает их в отсортированном порядке.
    X_unique = np.unique(X, axis=0)
    return X_unique

X = np.random.randint(4, 6, size=(10,3))
print(X)
print(get_unique_rows(X))

[[4 5 4]
 [4 5 5]
 [5 4 5]
 [4 5 5]
 [5 4 4]
 [5 5 5]
 [4 5 4]
 [4 5 4]
 [4 4 4]
 [4 4 4]]
[[4 4 4]
 [4 5 4]
 [4 5 5]
 [5 4 4]
 [5 4 5]
 [5 5 5]]
